# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('ctime', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=45)),
                ('uri', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'user_action_log',
                'managed': False,
            },
        ),
    ]
